# Generated by Django 5.0.7 on 2024-08-01 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KuyumcuKullanicilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100)),
                ('cins', models.CharField(max_length=100)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('milyem_per_cm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('birim', models.CharField(max_length=10)),
                ('alt_toplam', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('aciklama', models.TextField()),
                ('adet', models.IntegerField()),
                ('iscilik', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mm_per_cm', models.CharField(max_length=10)),
                ('isc_toplam', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('islem_tipi', models.CharField(choices=[('Altın Verildi', 'Altın Verildi'), ('Altın Alındı!', 'Altın Alındı!'), ('İşlem Yok', 'İşlem Yok'), ('', '---------')], default='', max_length=30)),
                ('tarih', models.DateTimeField(verbose_name='Tarih')),
                ('genel_toplam', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fark', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuyumcu_kullanicilar', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
